<a href="https://colab.research.google.com/github/SimbakNetmind/machine-learnig-curos/blob/Machine_learning/02_Regresion_Lineal_Ejercicio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ejercicio - Regresión lineal

Para prácticar el Análisis Exploratorio de Datos, vamos a usar una versión modificada del dataset [The Movies Dataset](https://www.kaggle.com/rounakbanik/the-movies-dataset) que contiene información sobre películas, información relacionada con el éxito de dichas películas en cuanto a popularidad y venta de entradas.

El dataset se encuentra en el archivo `data/movies.csv`, y consta de las siguientes columnas:

```
    belongs_to_collection (franquicia): Nombre de la franquicia a la cual pertenece la película.
    budget (presupuesto): Presupuesto de la película en dólares.
    genres (genero): Género de la pelicula.
    homepage (pagina_web): Página Web oficial de la película.
    imdb_id: ID de la película en IMDB.
    original_language (lenguaje): El lenguage original en el que se rodó la película.
    overview: Descripción de la película.
    popularity (popularidad): Puntuación de Popularidad.
    poster_path (poster): url del poster de la película
    production_companies (productores): Lista de compañias que produjeron la pelicula
    production_countries (pais): Pais de produccion de la película
    release_date (fecha_estreno): Fecha del estreno  de la película
    revenue (ventas): Ventas de entradas en dólares de la película.
    runtime (duracion): Duración en minutos de la película.
    status (estado): Estado de la película (estrenada, en producción, etc).
    tagline: Frase descriptiva de la película.
    title (titulo): Título de la película.
    vote_average (puntuacion): Puntuación media de la película.
    vote_count (n_votos): Número de votos.
```

Para este ejercicio la variable objetivo es las ventas en taquilla de la película (la columna `venta`)

In [1]:
import pandas as pd
import numpy as np

### **Cargar dataset**

In [4]:
pelis = pd.read_csv("sample_data/movies.csv")
print(pelis.shape)
pelis.head()

(1349, 16)

,franquicia,presupuesto,genero,pagina_web,imdb_id,lenguaje,popularidad,productores,pais,fecha_estreno,ventas,duracion,estado,titulo,puntuacion,n_votos
0,Father of the Bride Collection,NaN,Comedy,NaN,tt0113041,en,8.387519,Sandollar Productions,United States of America,1995-02-10,76578911.0,106.0,Released,Father of the Bride Part II,5.7,173.0
1,NaN,NaN,Drama,NaN,tt0112749,en,0.894647,Miramax,South Africa,1995-12-15,676525.0,106.0,Released,"Cry, the Beloved Country",6.7,13.0
2,Friday Collection,3500000.0,Comedy,http://www.newline.com/properties/friday.html,tt0113118,en,14.569650,New Line Cinema,United States of America,1995-04-26,28215918.0,91.0,Released,Friday,7.0,513.0
3,NaN,NaN,Comedy,NaN,tt0115697,en,8.963037,Paramount Pictures,United States of America,1996-02-01,32.0,87.0,Released,Black Sheep,6.0,124.0
4,NaN,12000000.0,Comedy,NaN,tt0116483,en,9.592265,Universal Pictures,United States of America,1996-02-16,41205099.0,92.0,Released,Happy Gilmore,6.5,767.0

### 01-Seleccionar las columnas numéricas sólo. Eliminar los valores nulos y reemplazarlos con 0

*(pista, usar los metodos `select_dtypes` y `fillna`)*

In [5]:
pelis.select_dtypes(np.number).head()

   presupuesto  popularidad      ventas  duracion  puntuacion  n_votos
0          NaN     8.387519  76578911.0     106.0         5.7    173.0
1          NaN     0.894647    676525.0     106.0         6.7     13.0
2    3500000.0    14.569650  28215918.0      91.0         7.0    513.0
3          NaN     8.963037        32.0      87.0         6.0    124.0
4   12000000.0     9.592265  41205099.0      92.0         6.5    767.0

In [8]:
pelis_numericas = pelis.select_dtypes(np.number).fillna(0)
pelis_numericas.head()

   presupuesto  popularidad      ventas  duracion  puntuacion  n_votos
0          0.0     8.387519  76578911.0     106.0         5.7    173.0
1          0.0     0.894647    676525.0     106.0         6.7     13.0
2    3500000.0    14.569650  28215918.0      91.0         7.0    513.0
3          0.0     8.963037        32.0      87.0         6.0    124.0
4   12000000.0     9.592265  41205099.0      92.0         6.5    767.0

### 02-Crear un modelo de regresion lineal (con scikit-learn) y entrenarlo en el dataset numéricos. La variable objetivo es `ventas`

In [9]:
from sklearn.linear_model import LinearRegression

In [12]:
variable_objetivo = "ventas"
variables_independientes = pelis_numericas.drop(columns=variable_objetivo).columns

print(f'Variable Objeivo: {variable_objetivo}')
print(f'Variable Independientes: {variables_independientes}')

Variable Objeivo: ventas
Variable Independientes: Index(['presupuesto', 'popularidad', 'duracion', 'puntuacion', 'n_votos'], dtype='object')

In [18]:
modelo = LinearRegression()
modelo.fit(X=pelis_numericas[variables_independientes],
           y=pelis_numericas[variable_objetivo])

LinearRegression()

### 03-Asignar una columna nueva con las predicciones al dataset original llamada `ventas_pred`

In [19]:
modelo.predict(pelis_numericas[variables_independientes])

array([13506241.85500558,  5503581.41530203, 38766797.47662728, ...,
        3565685.36813011,  4940243.61184623,  -470540.38735475])

In [20]:
pelis["ventas_pred"] = modelo.predict(
                            pelis_numericas[variables_independientes]
                        )
pelis.head()

,franquicia,presupuesto,genero,pagina_web,imdb_id,lenguaje,popularidad,productores,pais,fecha_estreno,ventas,duracion,estado,titulo,puntuacion,n_votos,ventas_pred
0,Father of the Bride Collection,NaN,Comedy,NaN,tt0113041,en,8.387519,Sandollar Productions,United States of America,1995-02-10,76578911.0,106.0,Released,Father of the Bride Part II,5.7,173.0,1.350624e+07
1,NaN,NaN,Drama,NaN,tt0112749,en,0.894647,Miramax,South Africa,1995-12-15,676525.0,106.0,Released,"Cry, the Beloved Country",6.7,13.0,5.503581e+06
2,Friday Collection,3500000.0,Comedy,http://www.newline.com/properties/friday.html,tt0113118,en,14.569650,New Line Cinema,United States of America,1995-04-26,28215918.0,91.0,Released,Friday,7.0,513.0,3.876680e+07
3,NaN,NaN,Comedy,NaN,tt0115697,en,8.963037,Paramount Pictures,United States of America,1996-02-01,32.0,87.0,Released,Black Sheep,6.0,124.0,9.331852e+06
4,NaN,12000000.0,Comedy,NaN,tt0116483,en,9.592265,Universal Pictures,United States of America,1996-02-16,41205099.0,92.0,Released,Happy Gilmore,6.5,767.0,6.737609e+07

In [21]:
pelis[["ventas", "ventas_pred"]].head()

       ventas   ventas_pred
0  76578911.0  1.350624e+07
1    676525.0  5.503581e+06
2  28215918.0  3.876680e+07
3        32.0  9.331852e+06
4  41205099.0  6.737609e+07